# Site settings
title: Hi, I'm Rohit.
description: Rohit Kulkarni' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rohit Kulkarni
user_job_title: Data Scientist
email: rohit.kulkarni [at] rutgers.edu
github_username:  rohitkulkarni08

exclude: ['package.json', 'src' , 'node_modules']
